name: Test

on:
    push:
    pull_request:
        branches: [ 2.x ]

    page_build:
    release:
        types: [ published, created, edited ]

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }} + ${{ matrix.variant }}'
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                dependencies:
                    - lowest
                    - highest
                php-version:
                    - '8.0'
                    - '8.1'
                    - '8.2'
                    - '8.3'
                variant: [normal]
                include:
                    - php-version: '8.0'
                      dependencies: highest
                      variant: 'doctrine/orm:~2.7 symfony/property-access:^6.0'
                    - php-version: '8.1'
                      dependencies: highest
                      variant: 'doctrine/orm:~2.7 symfony/property-access:^6.0'
                    - php-version: '8.2'
                      dependencies: highest
                      variant: 'doctrine/orm:~2.7 symfony/property-access:^7.0'
                    - php-version: '8.3'
                      dependencies: highest
                      variant: 'doctrine/orm:~2.7 symfony/property-access:^7.0'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Install variant
              if: matrix.variant != 'normal'
              run: composer require ${{ matrix.variant }} --no-update

            - name: 'Install Composer dependencies (${{ matrix.dependencies }})'
              uses: 'ramsey/composer-install@v1'
              with:
                  dependency-versions: '${{ matrix.dependencies }}'
                  composer-options: '--prefer-dist --prefer-stable'

            - name: Run Tests
              run: composer test
